//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by are_editer.rc
//
#define IDD_ARE_EDITER_DIALOG           102
#define IDR_HTML_DLGPAGE2               103
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_TAB1                 129
#define IDD_DIALOG_TAB2                 130
#define IDD_DIALOG_TAB4                 131
#define IDD_DIALOG_TAB3                 132
#define IDD_DIALOG_SUBTAB_CELL          133
#define IDD_DIALOG_SUBTAB_RECT          134
#define IDD_DIALOG_RTAB1                135
#define IDD_DIALOG_RTAB2                136
#define IDD_DIALOG_CTAB_TOOLS           137
#define IDD_DIALOG_SUBTAB_OTHER         138
#define IDD_DIALOG_CTAB_DISP            139
#define IDC_TAB1                        1000
#define IDC_BUTTON1                     1000
#define IDC_BUTTON_LOAD                 1001
#define IDC_BUTTON_SAVE                 1002
#define IDC_BUTTON3                     1002
#define IDC_CHECK1                      1003
#define IDC_EDIT1                       1004
#define IDC_BUTTON_REF1                 1005
#define IDC_CHECK_NOZT                  1005
#define IDC_EDIT2                       1006
#define IDC_SPIN1                       1006
#define IDC_BUTTON5                     1006
#define IDC_BUTTON_REF2                 1007
#define IDC_BUTTON_PREV10               1007
#define IDC_EDIT3                       1008
#define IDC_BUTTON_NEXT10               1008
#define IDC_BUTTON6                     1008
#define IDC_BUTTON_REF3                 1009
#define IDC_BUTTON_PREV_FIND            1009
#define IDC_EDIT4                       1010
#define IDC_BUTTON_NEXT_FIND            1010
#define IDC_BUTTON_REF4                 1011
#define IDC_BUTTON_PREV_BLANK           1011
#define IDC_EDIT5                       1012
#define IDC_BUTTON_NEXT_BLANK           1012
#define IDC_BUTTON_REF5                 1013
#define IDC_CHECK_SKIPLINK              1013
#define IDC_EDIT_COLOR_R                1013
#define IDC_EDIT6                       1014
#define IDC_BUTTON_REF6                 1015
#define IDC_BUTTON_COPY                 1015
#define IDC_EDIT_COLOR_B                1015
#define IDC_EDIT7                       1016
#define IDC_BUTTON_PASTE                1016
#define IDC_BUTTON_REF7                 1017
#define IDC_BUTTON_ERASE                1017
#define IDC_EDIT8                       1018
#define IDC_CHECK_SCA_BASEPOINT         1018
#define IDC_BUTTON_REF8                 1019
#define IDC_CHECK_ROT_BASEPOINT         1019
#define IDC_EDIT9                       1020
#define IDC_COMBO_MAG                   1020
#define IDC_BUTTON_REF9                 1021
#define IDC_COMBO_BGCOLOR               1021
#define IDC_EDIT10                      1022
#define IDC_CHECK_FLIPXTEST             1022
#define IDC_BUTTON_REF10                1023
#define IDC_CHECK_FLIPYTEST             1023
#define IDC_EDIT11                      1024
#define IDC_CHECK_LINK                  1024
#define IDC_BUTTON_REF11                1025
#define IDC_COMBO1                      1025
#define IDC_EDIT12                      1026
#define IDC_BUTTON_REF12                1027
#define IDC_CHECK_FLIPX                 1028
#define IDC_CHECK_FLIPY                 1029
#define IDC_RADIO1                      1031
#define IDC_RADIO2                      1032
#define IDC_RADIO3                      1033
#define IDC_RADIO4                      1034
#define IDC_RADIO5                      1035
#define IDC_BUTTON_RECT_KAS1            1036
#define IDC_RADIO8                      1036
#define IDC_BUTTON_RECT_KAS2            1037
#define IDC_STR_MAIN_STATUS             1037
#define IDC_RADIO9                      1037
#define IDC_BUTTON_RECT_KAS3            1038
#define IDC_BUTTON_LOAD_HEADER          1038
#define IDC_RADIO10                     1038
#define IDC_BUTTON_RECT_KUR1            1039
#define IDC_BUTTON_SAVE_HEADER          1039
#define IDC_TAB_RECT                    1039
#define IDC_BUTTON_RECT_KUR2            1040
#define IDC_TAB_CELL                    1040
#define IDC_BUTTON_RECT_KUR3            1041
#define IDC_BUTTON_APPLY                1041
#define IDC_BUTTON_RECT_ATK1            1042
#define IDC_BUTTON2                     1042
#define IDC_BUTTON_RECT_ATK2            1043
#define IDC_BUTTON_RECT_ATK3            1044
#define IDC_BUTTON_SETCURRENTBMP        1044
#define IDC_STR_INFO1                   1045
#define IDC_STR_INFO2                   1046
#define IDC_SPIN2                       1047
#define IDC_COMBO_RECT                  1048
#define IDC_INFO1                       1049
#define IDC_RADIO6                      1050
#define IDC_RADIO7                      1051
#define IDC_SLIDER1                     1053
#define IDC_SLIDER2                     1054
#define IDC_SLIDER3                     1055
#define IDC_SLIDER_COLOR_B              1056
#define IDC_CHECK_BLENDADD              1057
#define IDC_SLIDER_COLOR_A              1058
#define IDC_SLIDER_COLOR_R              1059
#define IDC_SLIDER_COLOR_G              1060
#define IDC_EDIT_COLOR_A                1061
#define IDC_EDIT_COLOR_G                1062
#define IDC_SLIDER_ROT                  1063
#define IDC_SLIDER_SCAX                 1064
#define IDC_EDIT_SCAX                   1065
#define IDC_SLIDER_SCAY                 1066
#define IDC_EDIT_SCAY                   1067
#define IDC_EDIT_ROT                    1068
#define IDC_RADIO_NONE                  1069
#define IDC_SLIDER_OFSX                 1070
#define IDC_SLIDER_OFSY                 1071
#define IDC_CHECK_NOZW                  1072
#define IDC_BUTTON_RFLIP0               1073
#define IDC_BUTTON_RFLIP1               1074
#define IDC_BUTTON_RFLIP2               1075
#define IDC_LIST1                       1075
#define IDC_BUTTON_RFLIP3               1076
#define IDC_BUTTON_RFLIP4               1077
#define IDC_BUTTON_RFLIP5               1078
#define IDC_BUTTON_RFLIP6               1079
#define IDC_BUTTON_RFLIP7               1080
#define IDC_BUTTON_RFLIP8               1081
#define IDC_BUTTON_RFLIP9               1082

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
